### PR TITLE
File names are corrected to correspond with files

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by mondain** [comment]
Those files were meant for the securing of jmx, they should probably be removed altogether. I think that renaming them jks (which is their file type) may cause confusion.

**Comment by solomax** [comment]
was setting RTMPS and found than names differ .... thought it was typo ...

**Comment by mondain** [comment]
I think I removed the rtmps / jks files for tomcat awhile back because self-signed certs don't seem to work very well or at all with flash player anymore.

**Comment by solomax** [comment]
I have created my own CA and added it to the browsers and to java
works as expected :)

**Comment by mondain** [comment]
Yeah those are extra steps that most of our users won't understand and they also may not want to add additional certs to their browsers. It would be better if we just provided a wiki describing the process for using self-signed certs.

**Pull request closed without merging**
